ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER gamemania IDENTIFIED BY gamemania
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER gamemania QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO gamemania;
GRANT "CONNECT" TO gamemania;
ALTER USER gamemania DEFAULT ROLE "RESOURCE","CONNECT";
