# Generated by Django 4.2.5 on 2023-09-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Género')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Nombre del Género')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('idVideojuego', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del videojuego')),
                ('nombreVideojuego', models.CharField(max_length=50, verbose_name='Nombre del videojuego')),
                ('precio', models.IntegerField(max_length=50, verbose_name='Precio del videojuego')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
            ],
        ),
    ]
