# Generated by Django 4.2.5 on 2023-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genero_videojuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.IntegerField(verbose_name='Precio del videojuego'),
        ),
    ]
