# Generated by Django 4.2.5 on 2023-09-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_genero_imagen_alter_videojuego_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
