# Generated by Django 4.2.5 on 2023-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_videojuego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del videojuego'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
