# Generated by Django 4.2.5 on 2023-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del videojuego'),
        ),
        migrations.AddField(
            model_name='genero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
