# Generated by Django 4.2.5 on 2023-09-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_genero_idgenero_alter_videojuego_idvideojuego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='descripcion',
        ),
    ]
