# Generated by Django 4.2.5 on 2023-09-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_genero_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fechalanzamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento del videojuego'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
