# Generated by Django 4.2.5 on 2023-09-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_videojuego_fechalanzamiento_alter_genero_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/'),
        ),
    ]
